apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: totalcompmx-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - totalcomp.mx
    secretName: totalcompmx-tls
  rules:
  - host: totalcomp.mx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: totalcompmx-frontend
            port:
              number: 80
